// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW3BYm-FusTJ7Rwdqj37w6WWyR4Ah3rnE',
    appId: '1:750467078445:web:281b1a062d8db831389ba4',
    messagingSenderId: '750467078445',
    projectId: 'moas-69c1b',
    authDomain: 'moas-69c1b.firebaseapp.com',
    storageBucket: 'moas-69c1b.firebasestorage.app',
    measurementId: 'G-ZXZ50E896H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUxhOXWh766h7uLKRNatpr6c6VWl13seY',
    appId: '1:750467078445:android:cffc9190b1820662389ba4',
    messagingSenderId: '750467078445',
    projectId: 'moas-69c1b',
    storageBucket: 'moas-69c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCABAAIIEpPAe5Q8Dn5dJ7nQDxdgj34mc',
    appId: '1:750467078445:ios:94636bf551a1cfd5389ba4',
    messagingSenderId: '750467078445',
    projectId: 'moas-69c1b',
    storageBucket: 'moas-69c1b.firebasestorage.app',
    iosBundleId: 'com.example.mohas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCABAAIIEpPAe5Q8Dn5dJ7nQDxdgj34mc',
    appId: '1:750467078445:ios:94636bf551a1cfd5389ba4',
    messagingSenderId: '750467078445',
    projectId: 'moas-69c1b',
    storageBucket: 'moas-69c1b.firebasestorage.app',
    iosBundleId: 'com.example.mohas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW3BYm-FusTJ7Rwdqj37w6WWyR4Ah3rnE',
    appId: '1:750467078445:web:64d226f5bac5aea6389ba4',
    messagingSenderId: '750467078445',
    projectId: 'moas-69c1b',
    authDomain: 'moas-69c1b.firebaseapp.com',
    storageBucket: 'moas-69c1b.firebasestorage.app',
    measurementId: 'G-RH90KGGX99',
  );
}
