name: mohas
description: MESMER Business Coaching Application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^17.2.4

  # Storage & Database
  sqflite: ^2.3.0
  path: ^1.9.0
  cloudinary_public: 0.23.1

  # Media & Location
  image_picker: ^1.0.0


  # Reports & Sharing
  excel: ^4.0.0
  path_provider: ^2.1.0
  share_plus: ^7.0.0

  # State Management
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.6

  # Utilities
  intl: ^0.18.1
  mobile_scanner: ^6.0.11
  google_fonts: ^6.2.1
  geocoding: ^4.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.10.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/Image/logo_1.png 
