# name: mohas
# description: "A new Flutter project."
# publish_to: 'none' # Prevent publishing to pub.dev

# version: 1.0.0+1

# environment:
#   sdk: ^3.5.4


# dependencies:
#   flutter:
#     sdk: flutter

#   # iOS style icons
 
#   # Firebase
#   firebase_core: ^4.4.0
#   cloud_firestore: ^6.1.2
#   firebase_auth: ^4.19.0

#   # File/Image handling
#   file_picker: ^10.3.10
#   image_picker: ^1.1.2
#   provider: ^6.1.1
#    # UI
#   cupertino_icons: ^1.0.6
  
#   # Utilities
#   intl: ^0.18.1
  
  

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^4.0.0

# flutter:
#   uses-material-design: true

#   # Assets
#   assets:
#     - assets/fonts/Inter/static/
#     - assets/fonts/Roboto/static/

#   # Fonts
#   fonts:
#     - family: Inter
#       fonts:
#         - asset: assets/fonts/Inter/static/Inter_24pt-Regular.ttf
#           weight: 400
#         - asset: assets/fonts/Inter/static/Inter_24pt-Medium.ttf
#           weight: 500
#         - asset: assets/fonts/Inter/static/Inter_24pt-SemiBold.ttf
#           weight: 600
#         - asset: assets/fonts/Inter/static/Inter_24pt-Bold.ttf
#           weight: 700

#     - family: Roboto
#       fonts:
#         - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
#           weight: 400




name: mohas
description: MESMER Business Coaching Application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.6.0
  flutter_local_notifications: ^17.0.0
  sqflite: ^2.3.0
  path: ^1.9.0
  cloudinary_public: ^0.8.2
  image_picker: ^1.0.0
  geolocator: ^12.0.0 
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  excel: ^4.0.0
  path_provider: ^2.1.0
  share_plus: ^7.0.0
  
  # State Management
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Utilities
  intl: ^0.18.1
  mobile_scanner: ^6.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
